#!/bin/bash

function getOptions() {
  while getopts "e:f:p:t" options; do
    case $options in
      f )
        FILENAME="+filename:$OPTARG"
        ;;
      e )
        EXTENSION="+extension:$OPTARG"
        ;;
      p )
        PAGE="&p=${OPTARG}"
        ;;
      t )
        FORK="+fork:true"
        ;;
      \? )
        exit 1
        ;;
    esac
  done
  PARSED_OPT_COUNT=$OPTIND
}

getOptions $@
shift $(( PARSED_OPT_COUNT - 1 ));

ORIGINAL_QUERY=$@
QUERY="$(urlencode "$( echo "$ORIGINAL_QUERY" | sed -e 's/ /+/g')")${FILENAME}${FORK}${EXTENSION}"
# URL="https://github.com/search?${PAGE}type=Code&q=$QUERY+in:file+filename:${FILENAME}${FORK}&ref=searchresults"
# URL="https://github.com/search?${PAGE}type=Code&q=$QUERY&ref=searchresults"
URL="https://github.com/search?${PAGE}type=Code&q=$QUERY"

#extension:java
#fork:true

# https://github.com/search?utf8=%E2%9C%93&q=extension%3Ajava+fork%3Atrue+mongo&type=Code&ref=searchresults

# echo "$URL" 1>&2
# exit 0

curl -s "$URL" \
| hxnormalize -xe \
| hxselect .code-list-item \
| sed -e 's/<a href="\//<a href="https:\/\/github.com\//g' \
| hxnormalize -xe
# \
# | pup '.code-list-item' \
# | hxnormalize -xe \
# | pup \
# | sed -e 's/<a href="\//<a href="https:\/\/github.com\//g'
#| hxremove .blob-num \

# curl -s "$URL" \
#  | html2text -ascii -nobs \
#  | sed \
#  -e '1,/^_Best_match/d' \
#  -e '/^How are these search results? Tell_us!$/,$d' \
#  | egrep --color -i "${ORIGINAL_QUERY}|$"

#  | sed -e '1,/^_Best_match/d' -e '/^Previous 1.*Next$/,$d'



# Skip to content
# Pull requests
# Issues
# Gist
#  @nasoym
#  Search more than 15M users
#  
# Search GitHub
# Search
# ProTip! For an advanced search, use some of our prefixes.
#
# Status API Training Shop Blog About
# © 2016 GitHub, Inc. Terms Privacy Security Contact Help
# Search cheat sheet (see all)
#
# GitHub’s search supports a variety of different operations. Here’s a quick cheat sheet for some of the common searches.
#
# For more information, visit our search help section.
#
# Basic search
#
# This search	Finds repositories with…
# cat stars:>100	Find cat repositories with greater than 100 stars.
# user:defunkt	Get all repositories from the user defunkt.
# tom location:"San Francisco, CA"	Find all tom users in "San Francisco, CA".
# join extension:coffee	Find all instances of join in code with coffee extension.
# NOT cat	Excludes all results containing cat
# Repository search 
#
# Repository search looks through the projects you have access to on GitHub. You can also filter the results:
#
# This search	Finds repositories with…
# cat stars:>100	Find cat repositories with greater than 100 stars.
# user:defunkt	Get all repositories from the user defunkt.
# pugs pushed:>2013-01-28	Pugs repositories pushed to since Jan 28, 2013.
# node.js forks:<200	Find all node.js repositories with less than 200 forks.
# jquery size:1024..4089	Find jquery repositories between the sizes 1024 and 4089 kB.
# gitx fork:true	Repository search includes forks of gitx.
# gitx fork:only	Repository search returns only forks of gitx.
# Code search 
#
# Code search looks through the files hosted on GitHub. You can also filter the results:
#
# This search	Finds repositories with…
# install repo:charles/privaterepo	Find all instances of install in code from the repository charles/privaterepo.
# shogun user:heroku	Find references to shogun from all public heroku repositories.
# join extension:coffee	Find all instances of join in code with coffee extension.
# system size:>1000	Find all instances of system in code of file size greater than 1000kbs.
# examples path:/docs/	Find all examples in the path /docs/.
# replace fork:true	Search replace in the source code of forks.
# Issue search 
#
# Issue search looks through issues and pull requests on GitHub. You can also filter the results:
#
# This search	Finds issues…
# encoding user:heroku	Encoding issues across the Heroku organization.
# cat is:open	Find cat issues that are open.
# strange comments:>42	Issues with more than 42 comments.
# hard label:bug	Hard issues labeled as a bug.
# author:mojombo	All issues authored by mojombo.
# mentions:tpope	All issues mentioning tpope.
# assignee:rtomayko	All issues assigned to rtomayko.
# exception created:>2012-12-31	Created since the beginning of 2013.
# exception updated:<2013-01-01	Last updated before 2013.
# User search 
#
# User search finds users with an account on GitHub. You can also filter the results:
#
# This search	Finds repositories with…
# fullname:"Linus Torvalds"	Find users with the full name "Linus Torvalds".
# tom location:"San Francisco, CA"	Find all tom users in "San Francisco, CA".
# chris followers:100..200	Find all chris users with followers between 100 and 200.
# ryan repos:>10	Find all ryan users with more than 10 repositories.
#
